-- Canonical stage_order (1–34) per §1 / funnel mapping. Single source for funnel + transitions.
CREATE OR REPLACE VIEW v_audit_staged AS
SELECT
    timestamp,
    actor,
    action,
    description,
    context,
    application_id,
    product_type,
    CASE action
        WHEN 'APPLICATION_STARTED' THEN 1
        WHEN 'APPLICATION_SUBMITTED' THEN 2
        WHEN 'DOCUMENTS_SUBMITTED' THEN 3
        WHEN 'ACCOUNT_MANAGER_ASSIGNED' THEN 4
        WHEN 'APP_ASSIGNED' THEN 5
        WHEN 'CUSTOMER_RELATION_REVIEW_STARTED' THEN 6
        WHEN 'CUSTOMER_RELATION_REVIEW_COMPLETED' THEN 7
        WHEN 'COMPLIANCE_REVIEW_STARTED' THEN 8
        WHEN 'INTERACTION_STARTED' THEN 9
        WHEN 'INTERACTION_SUBMITTED' THEN 10
        WHEN 'CUSTOMER_RELATION_INTERACTION_CANCELLED' THEN 11
        WHEN 'CUSTOMER_RELATION_INTERACTION_STARTED' THEN 12
        WHEN 'ANSWERS_EDIT_STARTED' THEN 13
        WHEN 'ANSWERS_EDIT_FINISHED' THEN 14
        WHEN 'LABEL_ADDED' THEN 15
        WHEN 'COMPLIANCE_REVIEW_COMPLETED' THEN 16
        WHEN 'APPLICATION_REJECTED' THEN 17
        WHEN 'APPLICATION_CANCELLED' THEN 18
        WHEN 'OFFER_PREPARED' THEN 19
        WHEN 'OFFER_SENT' THEN 20
        WHEN 'OFFER_RESPONSE' THEN 21
        WHEN 'OFFER_REFUSED' THEN 22
        WHEN 'VIDEO_IDENT_SENT' THEN 23
        WHEN 'VIDEO_IDENT_FINISHED' THEN 24
        WHEN 'ENROLLMENT_APPROVED' THEN 25
        WHEN 'MASTER_DATA_SUBMITTED' THEN 26
        ELSE 34
    END AS stage_order
FROM audit_logs;
